### PR TITLE
Resolved warnings in meraki_ms_switchport

### PR DESCRIPTION
**Pull request by y0rune**

### CODE REVIEW

**Comment by kbreit** [comment]
I can't test this as I lack a physical device which supports access policies on a trunk. Can you remove testing the access policy on the trunk port for now and we'll re-enable it later?

**Comment by y0rune** [comment]
I think if you do not have any issue to push it into master firstly, after that action we can think about the improvement on #350.

**Comment by kbreit** [comment]
I'll merge so we can focus on #350. As always, thank you for your contribution.

**Comment by y0rune** [comment]
I thank you for being part of that project <3

**Pull request merged**
