### PR TITLE
ms_switchport: Resolved issue with link_negotation

### PR DESCRIPTION
**Pull request by y0rune**
Fixes: #451

### CODE REVIEW

**Comment by kbreit** [comment]
Where did the list of options come from?

**Comment by y0rune** [comment]
At the work we have the MS355 and the uplink can be a that values. I added the attachment from GUI:
obraz

**Comment by kbreit** [comment]
Would you be able to run this playbook with a couple of the new options to ensure they work? Unfortunately, Meraki doesn't seem to publish these. Thanks.

**Comment by y0rune** [comment]
I will do it at end of the week due to I have to set up the lab env :C

**Comment by y0rune** [comment]
Okay. I tested it in the Meraki Dev Env.
image


I have also added the new tests to change it ;)

**Comment by y0rune** [comment]
I think it is ready to push into master after you check (@kbreit)
Thank you!

**Comment by kbreit** [comment]
Thanks for your update. Merging.

**Pull request merged**
