### PR TITLE
Resolve warnings meraki action batch

### PR DESCRIPTION
**Pull request by y0rune**

### CODE REVIEW

**Comment by kbreit** [comment]
I took a look at this and need to actually run the integration test. What is the purpose of the block? It's changing indentation of everything and making review tough. I may have missed it but I'm not seeing any linting errors that require a block.

**Comment by y0rune** [comment]
So maybe I will disable the prettier and I only change the errors for better reading. After that all changes I run the prettier command on all files. When we got a consensus of that PR I will do it for all files with warnings.

**Comment by kbreit** [comment]
That works. Please make that change and let's see how it looks then.

**Comment by y0rune** [comment]
I have added @kbreit. Please check it and after your approve I am going to work with the next tasks ;) 
Thank you!

**Comment by kbreit** [comment]
@y0rune I'm good with this as is. Do you have other changes you want in this PR before we move onto others?

**Comment by y0rune** [comment]
I will create PRs per test file to better communication. So I will work with next files. 
Please merge that changes and close the PR ;) 

Thank you!

**Comment by kbreit** [comment]
Thanks for the PR. Merging.

**Pull request merged**
