### PR TITLE
environmental productType is no more valid

### PR DESCRIPTION
**Pull request by mksbcisco**
There is a change in Meraki REST API and product type "environmental" is no more a valid value. In case one tries to pass it they are returned by this error from the API: 

fatal: [localhost]: FAILED! => {"changed": false, "msg": "HTTP error 400 - https://api.meraki.com/api/v1/organizations/ORG_ID/networks - Each element in 'productTypes' must be one of: 'wireless', 'appliance', 'switch', 'systemsManager', 'camera', 'cellularGateway' or 'sensor'", "response": "OK (unknown bytes)", "status": 400} 

There is a new value available in Meraki API "systemsManager".

The following changes have been done:
- Removed "environmental" value from the document of the type
- Added "systemsManager" value to the documentation of the type
- Removed "environmental" value from the choices of the net_type
- Added "systemsManager" value to the choices of the net_type

### CODE REVIEW

**Comment by y0rune** [comment]
LGTM! But I can not test it due to my environment do not have access to create a network in the dev env ;(

**Comment by kbreit** [comment]
I don't have systems manager to test either. But for this sort of PR I'm not worried about the change breaking things. But please add a change log entry and I can merge. Thank you for the contribution!

**Comment by mksbcisco** [comment]
Guys I am pretty new to this and will appreciate some help on this, can you guide me where is this change to be made and what kind of details I need to add

**Comment by kbreit** [comment]
> Guys I am pretty new to this and will appreciate some help on this, can you guide me where is this change to be made and what kind of details I need to add 
> 
> 

Of course. If you go into `changelogs/fragments` you'll see there's a few examples in there. Copy any of them to a new file (name doesn't matter much) and modify it based on the template. Let me know if that doesn't make sense and I can assist further.

**Comment by mksbcisco** [comment]
Ok this was fun, just did that. Let me know if this is ok

**Comment by kbreit** [comment]
Looks like that worked and made CI happy. I'll test to make sure it still runs (pretty sure it does) and merge. Hopefully new release this weekend or early next week. Thank you!!!

**Comment by mksbcisco** [comment]
Thanks and I appreciate work you have done in this tool.

**Comment by kbreit** [comment]
Thank you for your contribution. I hope to have a release in a few days.

**Pull request merged**
