### PR TITLE
Adds WPA3 spec to options

### LINKED ISSUE #81: meraki_ssid - New authentication types added
Meraki has added 'WPA3 Transition Mode' and 'WPA3 only' to the encryption mode. This should be added as an option.

### PR DESCRIPTION
**Pull request by jvanderaa**
I believe this covers what would be needed. I double checked the Meraki Dashboard SDK and it looks like it is those two options being added. Let me know if otherwise should be looked at.

Fixes #81

### CODE REVIEW

**Comment by kbreit** [comment]
Thank you for submitting this PR. I’ve held off adding support as the documentation I’ve seen says it’s beta and you need to work with Meraki for the feature to be enabled. Do you have documentation stating otherwise? I’m not opposed to merging this but I’d like to make sure it’s properly documented. I’ll write integration tests too.

**Comment by jvanderaa** [comment]
No issue holding off. I have not seen anything different to what you have.

I had a few free hours today and looked to contribute where I could in some of the collections. 

Feel free to defer, decline, or what would be needed.

**Comment by kbreit** [comment]
Are you able to write an integration test against this? Also add some documentation to say “Hey WPA3 only works if you ask nicely.” If you’re unable to get the integration tests to work just let me know. My template is a mess and hard to figure out, even for me.

**Comment by jvanderaa** [comment]
I will try to take a look at the integration tests and how they are being done.

I did reach out to support if they could give me access or a postman collection with the response. They mentioned we just need to use the latest beta version of software to get WPA3 settings enabled.

**Comment by kbreit** [comment]
Integration test would be in `tests/integration/targets/meraki_ssid`. I think one test calling the WPA3 method should be enough as it doesn’t really add any code flows.

**Comment by kbreit** [comment]
Are you able to modify the PR to merge into `release/1.0` or something like that? I created branches to keep maintaining 1.0 and started work on 2.0 which will use the v1 of the Meraki API?

**Comment by jvanderaa** [comment]
I only see master and release/2.0 at the moment.

**Comment by kbreit** [comment]
For good reason. I never pushed it. I’ll push today.

**Comment by kbreit** [comment]
Please try  now.

**Comment by kbreit** [comment]
@jvanderaa I am able to change the target branch. Do you mind if I give it a try? Make sure you keep a local copy of changes just in case.

**Comment by jvanderaa** [comment]
Success on changing the target branch. Now I get to work on figuring out the unit testing today at some point

**Comment by kbreit** [comment]
The integration tests are a simple playbook. But the inventory.networking has…grown organically. In other words it’s a mess and is on my plan after I release 2.0. Let me know if you have questions though.

**Comment by jvanderaa** [comment]
@kbreit how do you go about testing on the local machine? I've been doing mostly Dockerfile and a command execution tool (Make or Python Invoke).

**Comment by kbreit** [comment]
That would work well enough. Just show the playbook and output.

I use a whole setup using `Ansible-test` which invokes Docker and runs through integration tests.

**Comment by jvanderaa** [comment]
Ok, I think I have figured out how painful it is to get setup with testing because of ansible-test. For others and maybe a contributing guide:

1. Create a new directory called `ansible_collections` somewhere not in the root since having that directory in the root would then put it into your Ansible default config
2. Create a directory nested under `ansible_collections` named `cisco` for the namespace
3. cd into this `cisco` directory
4. `git clone <clone_url> meraki` to clone this repo with the proper namespace and collection name

That would take care of being able to run `ansible-test sanity --docker -v --color --python 3.6` locally and not rely on GitHub actions.

Although interestingly enough this repo pass on GH actions, but failed locally.

**Comment by kbreit** [comment]
Good call on updating the guide. The README was right until I moved it into collections but then that changed the directory structure. Which version of Ansible are you using locally? 2.9 and 2.10 have very different tests.

**Comment by kbreit** [comment]
> I did reach out to support if they could give me access or a postman collection with the response. They mentioned we just need to use the latest beta version of software to get WPA3 settings enabled.

Testing this tonight I noticed my environment doesn't have a WPA3 AP in it. Were you able to run through the entire test suite?

**Comment by kbreit** [comment]
@jvanderaa I am very confused why it's still showing a conflict. Would you please create a brand new PR and see if that helps?

**Pull request merged**
